version: '3.8'

services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /src
    container_name: python
    networks:
      - app
    depends_on:
      - db
    volumes:
      - ./src:/src
  db:
    image: postgres
    container_name: db
    ports:
      - "5432:5432"
    networks:
      - app
    environment:
      - POSTGRES_PASSWORD=root
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com  
      PGADMIN_DEFAULT_PASSWORD: admin     
    ports:
      - "8080:80"
    networks:
      - app
    depends_on:
      - db
networks:
 app:
                                                                                           

    